// generated by stringer -type=TextureTarget,RenderbufferFormat,FramebufferAttachment,BufferUsage,Feature,Orientation,Facet,ShaderType,BlendEquation -output=stringers.go; DO NOT EDIT

package gfx

import "fmt"

const _TextureTarget_name = "Texture2DTextureCubeMapPositiveXTextureCubeMapNegativeXTextureCubeMapPositiveYTextureCubeMapNegativeYTextureCubeMapPositiveZTextureCubeMapNegativeZ"

var _TextureTarget_index = [...]uint8{0, 9, 32, 55, 78, 101, 124, 147}

func (i TextureTarget) String() string {
	if i < 0 || i+1 >= TextureTarget(len(_TextureTarget_index)) {
		return fmt.Sprintf("TextureTarget(%d)", i)
	}
	return _TextureTarget_name[_TextureTarget_index[i]:_TextureTarget_index[i+1]]
}

const _RenderbufferFormat_name = "RGBA4RGB565RGB5A1DepthComponent16"

var _RenderbufferFormat_index = [...]uint8{0, 5, 11, 17, 33}

func (i RenderbufferFormat) String() string {
	i -= 7
	if i < 0 || i+1 >= RenderbufferFormat(len(_RenderbufferFormat_index)) {
		return fmt.Sprintf("RenderbufferFormat(%d)", i+7)
	}
	return _RenderbufferFormat_name[_RenderbufferFormat_index[i]:_RenderbufferFormat_index[i+1]]
}

const _FramebufferAttachment_name = "ColorAttachment0DepthAttachmentStencilAttachmentDepthStencilAttachment"

var _FramebufferAttachment_index = [...]uint8{0, 16, 31, 48, 70}

func (i FramebufferAttachment) String() string {
	i -= 11
	if i < 0 || i+1 >= FramebufferAttachment(len(_FramebufferAttachment_index)) {
		return fmt.Sprintf("FramebufferAttachment(%d)", i+11)
	}
	return _FramebufferAttachment_name[_FramebufferAttachment_index[i]:_FramebufferAttachment_index[i+1]]
}

const _BufferUsage_name = "StaticDrawDynamicDrawStreamDraw"

var _BufferUsage_index = [...]uint8{0, 10, 21, 31}

func (i BufferUsage) String() string {
	i -= 15
	if i < 0 || i+1 >= BufferUsage(len(_BufferUsage_index)) {
		return fmt.Sprintf("BufferUsage(%d)", i+15)
	}
	return _BufferUsage_name[_BufferUsage_index[i]:_BufferUsage_index[i+1]]
}

const _Feature_name = "BlendDepthTestCullFacePolygonOffsetFillScissorTest"

var _Feature_index = [...]uint8{0, 5, 14, 22, 39, 50}

func (i Feature) String() string {
	i -= 18
	if i < 0 || i+1 >= Feature(len(_Feature_index)) {
		return fmt.Sprintf("Feature(%d)", i+18)
	}
	return _Feature_name[_Feature_index[i]:_Feature_index[i+1]]
}

const _Orientation_name = "CCWCW"

var _Orientation_index = [...]uint8{0, 3, 5}

func (i Orientation) String() string {
	i -= 23
	if i < 0 || i+1 >= Orientation(len(_Orientation_index)) {
		return fmt.Sprintf("Orientation(%d)", i+23)
	}
	return _Orientation_name[_Orientation_index[i]:_Orientation_index[i+1]]
}

const _Facet_name = "FrontBackFrontAndBack"

var _Facet_index = [...]uint8{0, 5, 9, 21}

func (i Facet) String() string {
	i -= 25
	if i < 0 || i+1 >= Facet(len(_Facet_index)) {
		return fmt.Sprintf("Facet(%d)", i+25)
	}
	return _Facet_name[_Facet_index[i]:_Facet_index[i+1]]
}

const _ShaderType_name = "VertexShaderFragmentShader"

var _ShaderType_index = [...]uint8{0, 12, 26}

func (i ShaderType) String() string {
	i -= 28
	if i < 0 || i+1 >= ShaderType(len(_ShaderType_index)) {
		return fmt.Sprintf("ShaderType(%d)", i+28)
	}
	return _ShaderType_name[_ShaderType_index[i]:_ShaderType_index[i+1]]
}

const _BlendEquation_name = "FuncAddFuncSubtractFuncReverseSubtract"

var _BlendEquation_index = [...]uint8{0, 7, 19, 38}

func (i BlendEquation) String() string {
	i -= 30
	if i < 0 || i+1 >= BlendEquation(len(_BlendEquation_index)) {
		return fmt.Sprintf("BlendEquation(%d)", i+30)
	}
	return _BlendEquation_name[_BlendEquation_index[i]:_BlendEquation_index[i+1]]
}
